# Generated by Django 5.0.6 on 2024-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oc_diff', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('indicater', models.CharField(max_length=100)),
            ],
        ),
    ]
